easy_admin:

    entities:
        # List the entity class name you want to manage
        - App\Entity\Folder
        - App\Entity\Tutorial
        - App\Entity\Video
        - App\Entity\Comment
        - App\Entity\User
        - App\Entity\Category
        - App\Entity\Tag
        - App\Entity\Question
        - App\Entity\Company
